/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cms.gui;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

import cms.db.Database;
import cms.validation.Validation;
import java.awt.event.ActionEvent;

/**
 *
 * @author biraj
 */
public class ModulesForm extends javax.swing.JFrame {
    private boolean isEditMode;
    private int selectedIndex;
    private JTable table;

    /**
     * Creates new form ModulesForm
     */
    public ModulesForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        jButton1.setText("Add");
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/icons/add.png")));
        this.setTitle("Add Module");
        Database db = new Database();
        db.fetchCourseIDsFromDatabase(courseID);
        db.fetchInstructorNamesFromDatabase(assignTutor);
    }

    public ModulesForm(boolean isEditMode, JTable table, int selectedIndex) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.isEditMode = isEditMode;
        this.selectedIndex = selectedIndex;
        this.table = table;
        jButton1.setText("Update");
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/icons/edit.png")));
        this.setTitle("Update Module");
        Database db = new Database();
        db.fetchCourseIDsFromDatabase(courseID);
        db.fetchInstructorNamesFromDatabase(assignTutor);
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        moduleName.setText(model.getValueAt(selectedIndex, 1).toString());
        courseID.setSelectedItem(model.getValueAt(selectedIndex, 2).toString());
        assignTutor.setSelectedItem(model.getValueAt(selectedIndex, 3).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        moduleName = new javax.swing.JTextField();
        courseID = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        assignTutor = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(123, 95, 241));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(123, 95, 241));

        jLabel10.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/icons/modules.png"))); // NOI18N
        jLabel10.setText("Module");

        moduleName.setBackground(new java.awt.Color(123, 95, 241));
        moduleName.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        moduleName.setForeground(new java.awt.Color(255, 255, 255));
        moduleName.setBorder(javax.swing.BorderFactory.createTitledBorder(
                new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Module Name",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP,
                new java.awt.Font("Poppins Medium", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        moduleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });

        courseID.setBackground(new java.awt.Color(123, 95, 241));
        courseID.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        courseID.setForeground(new java.awt.Color(255, 255, 255));
        courseID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select any one" }));
        courseID.setPreferredSize(new java.awt.Dimension(72, 45));

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Course ID");

        assignTutor.setBackground(new java.awt.Color(123, 95, 241));
        assignTutor.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        assignTutor.setForeground(new java.awt.Color(255, 255, 255));
        assignTutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select any one" }));
        assignTutor.setPreferredSize(new java.awt.Dimension(72, 45));
        assignTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTutorActionPerformed(evt);
            }

            private void assignTutorActionPerformed(ActionEvent evt) {
                // TODO Auto-generated method stub
            }
        });

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Assign Tutor");

        jButton1.setBackground(new java.awt.Color(250, 112, 112));
        jButton1.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cms/icons/add.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }

            private void jButton1ActionPerformed(ActionEvent evt) {
                // TODO Auto-generated method stub
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(courseID, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(moduleName)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(assignTutor, 0, 362, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moduleName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(courseID, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(assignTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(18, Short.MAX_VALUE)));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton1MouseClicked
        if (isEditMode) {
            // Update existing module
            int id = Integer.parseInt(table.getValueAt(selectedIndex, 0).toString());
            String module_name = moduleName.getText();
            String course_id = courseID.getSelectedItem().toString();
            String tutor_name = assignTutor.getSelectedItem().toString();
            Validation val = new Validation();
            if (val.validateModuleInputs(id, module_name, course_id, tutor_name)) {
                Database db = new Database();
                db.updateModules(id, module_name, Integer.parseInt(course_id), tutor_name);
                dispose();
                JOptionPane.showMessageDialog(null, "Module updated successfully");
                Dashboard.updateModulesTable();
                // Reset the form
                moduleName.setText("");
                courseID.setSelectedIndex(0);
                assignTutor.setSelectedIndex(0);
            }
        } else {
            // Add new module
            String module_name = moduleName.getText();
            String course_id = courseID.getSelectedItem().toString();
            String tutor_name = assignTutor.getSelectedItem().toString();
            Validation val = new Validation();
            if (val.validateModuleInputs(module_name, course_id, tutor_name)) {
                Database db = new Database();
                db.addModules(module_name, Integer.parseInt(course_id), tutor_name);
                dispose();
                JOptionPane.showMessageDialog(null, "Module added successfully");
                Dashboard.updateModulesTable();
                Dashboard.updateCount();
                // Reset the form
                moduleName.setText("");
                courseID.setSelectedIndex(0);
                assignTutor.setSelectedIndex(0);
            }
        }
    }// GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModulesForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModulesForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModulesForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModulesForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModulesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> assignTutor;
    private javax.swing.JComboBox<String> courseID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField moduleName;
    // End of variables declaration//GEN-END:variables
}
